import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen max-h-screen text-cente flex flex-col">
      <Header />
      <main className="p-4 h-full bg-slate-200 grow">{children}</main>
    </div>
  );
}
