// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BoardId } from './Board';
import type { RoleId } from './Role';

/** Identifier type for public.board_user_role */
export type BoardUserRoleId = string & { __brand: 'BoardUserRoleId' };

/** Represents the table public.board_user_role */
export default interface BoardUserRole {
  id: BoardUserRoleId;

  userId: string;

  boardId: BoardId;

  roleId: RoleId;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.board_user_role */
export interface BoardUserRoleInitializer {
  /** Default value: uuid_generate_v4() */
  id?: BoardUserRoleId;

  userId: string;

  boardId: BoardId;

  roleId: RoleId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;
}

/** Represents the mutator for the table public.board_user_role */
export interface BoardUserRoleMutator {
  id?: BoardUserRoleId;

  userId?: string;

  boardId?: BoardId;

  roleId?: RoleId;

  createdAt?: Date;

  updatedAt?: Date;
}
