// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BoardId } from './Board';

/** Identifier type for public.board_column */
export type BoardColumnId = string & { __brand: 'BoardColumnId' };

/** Represents the table public.board_column */
export default interface BoardColumn {
  id: BoardColumnId;

  title: string;

  boardId: BoardId;

  index: number;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.board_column */
export interface BoardColumnInitializer {
  /** Default value: uuid_generate_v4() */
  id?: BoardColumnId;

  title: string;

  boardId: BoardId;

  index: number;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;
}

/** Represents the mutator for the table public.board_column */
export interface BoardColumnMutator {
  id?: BoardColumnId;

  title?: string;

  boardId?: BoardId;

  index?: number;

  createdAt?: Date;

  updatedAt?: Date;
}
