// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BoardId } from './Board';
import type { RoleId } from './Role';

/** Identifier type for public.BoardUserRole */
export type BoardUserRoleId = string & { __brand: 'BoardUserRoleId' };

/** Represents the table public.BoardUserRole */
export default interface BoardUserRole {
  id: BoardUserRoleId;

  userId: string;

  boardId: BoardId;

  roleId: RoleId;
}

/** Represents the initializer for the table public.BoardUserRole */
export interface BoardUserRoleInitializer {
  id: BoardUserRoleId;

  userId: string;

  boardId: BoardId;

  roleId: RoleId;
}

/** Represents the mutator for the table public.BoardUserRole */
export interface BoardUserRoleMutator {
  id?: BoardUserRoleId;

  userId?: string;

  boardId?: BoardId;

  roleId?: RoleId;
}
