// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Board */
export type BoardId = string & { __brand: 'BoardId' };

/** Represents the table public.Board */
export default interface Board {
  id: BoardId;

  title: string;

  createdByUserId: string;

  createdAt: Date;
}

/** Represents the initializer for the table public.Board */
export interface BoardInitializer {
  id: BoardId;

  title: string;

  createdByUserId: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;
}

/** Represents the mutator for the table public.Board */
export interface BoardMutator {
  id?: BoardId;

  title?: string;

  createdByUserId?: string;

  createdAt?: Date;
}
