// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BoardId } from './Board';

/** Identifier type for public.Column */
export type ColumnId = string & { __brand: 'ColumnId' };

/** Represents the table public.Column */
export default interface Column {
  id: ColumnId;

  title: string;

  boardId: BoardId;

  index: number;

  createdAt: Date;
}

/** Represents the initializer for the table public.Column */
export interface ColumnInitializer {
  id: ColumnId;

  title: string;

  boardId: BoardId;

  index: number;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;
}

/** Represents the mutator for the table public.Column */
export interface ColumnMutator {
  id?: ColumnId;

  title?: string;

  boardId?: BoardId;

  index?: number;

  createdAt?: Date;
}
