// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.role */
export type RoleId = number & { __brand: 'RoleId' };

/** Represents the table public.role */
export default interface Role {
  id: RoleId;

  name: string;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.role */
export interface RoleInitializer {
  /** Default value: nextval('role_id_seq'::regclass) */
  id?: RoleId;

  name: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;
}

/** Represents the mutator for the table public.role */
export interface RoleMutator {
  id?: RoleId;

  name?: string;

  createdAt?: Date;

  updatedAt?: Date;
}
