// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Role */
export type RoleId = number & { __brand: 'RoleId' };

/** Represents the table public.Role */
export default interface Role {
  id: RoleId;

  name: string;
}

/** Represents the initializer for the table public.Role */
export interface RoleInitializer {
  /** Default value: nextval('"Role_id_seq"'::regclass) */
  id?: RoleId;

  name: string;
}

/** Represents the mutator for the table public.Role */
export interface RoleMutator {
  id?: RoleId;

  name?: string;
}
