// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { BoardColumnId } from './BoardColumn';

/** Identifier type for public.ticket */
export type TicketId = string & { __brand: 'TicketId' };

/** Represents the table public.ticket */
export default interface Ticket {
  id: TicketId;

  title: string;

  description: string | null;

  columnId: BoardColumnId;

  index: number;

  createdByUserId: string;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.ticket */
export interface TicketInitializer {
  /** Default value: uuid_generate_v4() */
  id?: TicketId;

  title: string;

  description?: string | null;

  columnId: BoardColumnId;

  index: number;

  createdByUserId: string;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;
}

/** Represents the mutator for the table public.ticket */
export interface TicketMutator {
  id?: TicketId;

  title?: string;

  description?: string | null;

  columnId?: BoardColumnId;

  index?: number;

  createdByUserId?: string;

  createdAt?: Date;

  updatedAt?: Date;
}
