// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnId } from './Column';

/** Identifier type for public.Ticket */
export type TicketId = string & { __brand: 'TicketId' };

/** Represents the table public.Ticket */
export default interface Ticket {
  id: TicketId;

  title: string;

  description: string;

  columnId: ColumnId;

  createdByUserId: string;

  index: number;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.Ticket */
export interface TicketInitializer {
  id: TicketId;

  title: string;

  description: string;

  columnId: ColumnId;

  createdByUserId: string;

  index: number;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updatedAt?: Date;
}

/** Represents the mutator for the table public.Ticket */
export interface TicketMutator {
  id?: TicketId;

  title?: string;

  description?: string;

  columnId?: ColumnId;

  createdByUserId?: string;

  index?: number;

  createdAt?: Date;

  updatedAt?: Date;
}
