// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TicketId } from './Ticket';

/** Identifier type for public.TicketAssignedToUser */
export type TicketAssignedToUserId = string & { __brand: 'TicketAssignedToUserId' };

/** Represents the table public.TicketAssignedToUser */
export default interface TicketAssignedToUser {
  id: TicketAssignedToUserId;

  userId: string;

  ticketId: TicketId;
}

/** Represents the initializer for the table public.TicketAssignedToUser */
export interface TicketAssignedToUserInitializer {
  id: TicketAssignedToUserId;

  userId: string;

  ticketId: TicketId;
}

/** Represents the mutator for the table public.TicketAssignedToUser */
export interface TicketAssignedToUserMutator {
  id?: TicketAssignedToUserId;

  userId?: string;

  ticketId?: TicketId;
}
