// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from 'knex';
import type { default as Board, BoardInitializer, BoardMutator } from './public/Board';
import type { default as BoardColumn, BoardColumnInitializer, BoardColumnMutator } from './public/BoardColumn';
import type { default as Ticket, TicketInitializer, TicketMutator } from './public/Ticket';
import type { default as Role, RoleInitializer, RoleMutator } from './public/Role';
import type { default as TicketAssignedToUser, TicketAssignedToUserInitializer, TicketAssignedToUserMutator } from './public/TicketAssignedToUser';
import type { default as BoardUserRole, BoardUserRoleInitializer, BoardUserRoleMutator } from './public/BoardUserRole';

declare module 'knex/types/tables' {
  interface Tables {
    'board': Knex.CompositeTableType<Board, BoardInitializer, BoardMutator>;
    'board_column': Knex.CompositeTableType<BoardColumn, BoardColumnInitializer, BoardColumnMutator>;
    'ticket': Knex.CompositeTableType<Ticket, TicketInitializer, TicketMutator>;
    'role': Knex.CompositeTableType<Role, RoleInitializer, RoleMutator>;
    'ticket_assigned_to_user': Knex.CompositeTableType<TicketAssignedToUser, TicketAssignedToUserInitializer, TicketAssignedToUserMutator>;
    'board_user_role': Knex.CompositeTableType<BoardUserRole, BoardUserRoleInitializer, BoardUserRoleMutator>;
  }
}
