// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from 'knex';
import type { default as PrismaMigrations, PrismaMigrationsInitializer, PrismaMigrationsMutator } from './public/PrismaMigrations';
import type { default as Ticket, TicketInitializer, TicketMutator } from './public/Ticket';
import type { default as TicketAssignedToUser, TicketAssignedToUserInitializer, TicketAssignedToUserMutator } from './public/TicketAssignedToUser';
import type { default as Board, BoardInitializer, BoardMutator } from './public/Board';
import type { default as BoardUserRole, BoardUserRoleInitializer, BoardUserRoleMutator } from './public/BoardUserRole';
import type { default as Role, RoleInitializer, RoleMutator } from './public/Role';
import type { default as Column, ColumnInitializer, ColumnMutator } from './public/Column';

declare module 'knex/types/tables' {
  interface Tables {
    '_prisma_migrations': Knex.CompositeTableType<PrismaMigrations, PrismaMigrationsInitializer, PrismaMigrationsMutator>;
    'Ticket': Knex.CompositeTableType<Ticket, TicketInitializer, TicketMutator>;
    'TicketAssignedToUser': Knex.CompositeTableType<TicketAssignedToUser, TicketAssignedToUserInitializer, TicketAssignedToUserMutator>;
    'Board': Knex.CompositeTableType<Board, BoardInitializer, BoardMutator>;
    'BoardUserRole': Knex.CompositeTableType<BoardUserRole, BoardUserRoleInitializer, BoardUserRoleMutator>;
    'Role': Knex.CompositeTableType<Role, RoleInitializer, RoleMutator>;
    'Column': Knex.CompositeTableType<Column, ColumnInitializer, ColumnMutator>;
  }
}
